from django.urls import path
from . import views

urlpatterns = [
    path("", views.migrate, name="migrate"),
    path("report", views.report, name="report"),
    path("sequenced_files", views.sequenced_files, name="sequenced-files"),
    path("sequenced_files_opposite", views.sequenced_files_opposite, name="sequenced-files-opposite"),
    path("variant", views.variant, name="variant"),
    path("gene", views.gene, name="gene"),
    path("lookup", views.lookup_all_data, name="lookup-all-data"),
    path("consolidated_data", views.consolidated_data, name="consolidated-data"),
    path("body_sites", views.import_body_sites, name="import-body-sites"),
    path("airtable", views.airtable_consolidated_data, name="airtable-consolidated-data"),
    path("qpcr_consolidated_data", views.qpcr_consolidated_data, name="qpcr_consolidated_data"),
    path("qpcr_at_na", views.qpcr_at_na, name="qpcr_at_na"),
    path("qpcr_at_sl", views.qpcr_at_sl, name="qpcr_at_sl"),
    path("create_file_from_file", views.create_file_from_file, name="create_file_from_file"),
    path("qpcr_at_seqrun", views.qpcr_at_seqrun, name="qpcr_at_seqrun"),
    path("qpcr_at_leftover", views.qpcr_at_leftover, name="qpcr_at_leftover"),
    path("import_body_sites", views.import_body_sites, name="import_body_sites"),
    path("remove_NAN", views.remove_NAN, name="remove_NAN"),
    # path("uploads_barcodes", views.uploads_barcodes, name="uploads_barcodes"),
    path("uploads_baits", views.uploads_baits, name="uploads_baits"),
    path("upload_file_tree", views.upload_file_tree, name="upload_file_tree"),
    path("match_new_files", views.match_new_files, name="match_new_files"),
    path("block_scan_number", views.block_scan_number, name="block_scan_number"),
    path("create_fastq_from_file", views.create_fastq_from_file, name="create_fastq_from_file"),
    path("upload_unregistered", views.upload_unregistered, name="upload_unregistered"),
    path("prepare_report", views.prepare_report, name="prepare_report"),
    path("check_na", views.check_na, name="check_na"),
    path("check_na3", views.check_na3, name="check_na3"),
    path("check_na2", views.check_na2, name="check_na2"),
    path("check_patient", views.check_patient, name="check_patient"),
    path("check_block", views.check_block, name="check_block"),
    path("check_block2", views.check_block2, name="check_block2"),
    path("check_block3", views.check_block3, name="check_block3"),
    path("upload_file_tree_all_md5", views.upload_file_tree_all_md5, name="upload_file_tree_all_md5"),
    path("upload_file_tree_all_md5_2", views.upload_file_tree_all_md5_2, name="upload_file_tree_all_md5_2"),
    path("check_sample_library", views.check_sample_library, name="check_sample_library"),
    path("check_seq_run", views.check_seq_run, name="check_seq_run"),
    path("check_dna_rna", views.check_dna_rna, name="check_dna_rna"),
    path("check_areas_airtable", views.check_areas_airtable, name="check_areas_airtable"),
    path("check_patients_airtable", views.check_patients_airtable, name="check_patients_airtable"),
    path("blocks_sl_at", views.blocks_sl_at, name="blocks_sl_at"),
    path("check_projects_airtable", views.check_projects_airtable, name="check_projects_airtable"),
    path("create_file_from_df_fq", views.create_file_from_df_fq, name="create_file_from_df_fq"),
]
