# Generated by Django 3.2.15 on 2022-09-06 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(default='XY', max_length=6, unique=True)),
                ('pi', models.CharField(blank=True, choices=[('BB', 'Boris Bastian'), ('IY', 'Iwei Yeh')], default='BB', max_length=2, null=True)),
                ('speedtype', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_start', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'managed': True,
            },
        ),
    ]
