# Generated by Django 3.2.15 on 2023-07-26 12:58

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('abbreviation', models.CharField(default='XY', help_text='Requires a unique identifier for each Project.', max_length=7, unique=True, verbose_name='Abbreviation')),
                ('pi', models.CharField(blank=True, choices=[('BB', 'Boris Bastian'), ('IY', 'Iwei Yeh')], default='BB', max_length=2, null=True, verbose_name='Principal Investigator')),
                ('speedtype', models.CharField(blank=True, max_length=50, null=True, verbose_name='Speed Type')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('date_start', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Start Date')),
                ('pr_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Project ID')),
                ('researcher', models.ManyToManyField(null=True, related_name='researcher_projects', to=settings.AUTH_USER_MODEL, verbose_name='Researcher')),
                ('technician', models.ManyToManyField(null=True, related_name='technician_projects', to=settings.AUTH_USER_MODEL, verbose_name='Technician')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'managed': True,
            },
        ),
    ]
