# Generated by Django 3.0.5 on 2020-07-15 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('pi', models.CharField(blank=True, choices=[('BB', 'Boris Bastian'), ('IY', 'Iwei Yeh')], default='BB', max_length=2, null=True)),
                ('speedtype', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_start', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'projects',
                'managed': True,
            },
        ),
    ]
