# Generated by Django 3.0.5 on 2020-07-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='abbreviations',
            field=models.CharField(default='XY', max_length=6),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
