# Generated by Django 3.0.5 on 2020-07-15 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200715_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'managed': True, 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='abbreviations',
            new_name='abbreviation',
        ),
    ]
