# Generated by Django 3.0.5 on 2020-07-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200715_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='abbreviation',
            field=models.CharField(default='XY', max_length=6, unique=True),
        ),
    ]
