# Generated by Django 3.2.15 on 2023-09-18 21:07

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='researcher',
            field=models.ManyToManyField(blank=True, null=True, related_name='researcher_projects', to=settings.AUTH_USER_MODEL, verbose_name='Researcher'),
        ),
        migrations.AddField(
            model_name='projects',
            name='technician',
            field=models.ManyToManyField(null=True, related_name='technician_projects', to=settings.AUTH_USER_MODEL, verbose_name='Technician'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='abbreviation',
            field=models.CharField(default='XY', help_text='Requires a unique identifier for each Project.', max_length=7, unique=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='pi',
            field=models.CharField(blank=True, choices=[('BB', 'Boris Bastian'), ('IY', 'Iwei Yeh')], default='BB', max_length=2, null=True, verbose_name='Principal Investigator'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='pr_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Project ID'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='speedtype',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Speed Type'),
        ),
    ]
