# Generated by Django 3.2.15 on 2023-07-26 12:58


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('body', '0001_initial'),
        ('projects', '0001_initial'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('bl_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
                ('age', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1, message='Minimum age is 0.1 years'), django.core.validators.MaxValueValidator(120, message='Maximum age is 120 years')])),
                ('ulceration', models.BooleanField(blank=True, null=True)),
                ('thickness', models.FloatField(blank=True, help_text='float field ex. 0.1', null=True)),
                ('mitoses', models.IntegerField(blank=True, null=True)),
                ('p_stage', models.CharField(blank=True, choices=[('Tis', 'Tis'), ('T1a', 'T1a'), ('T1b', 'T1b'), ('T2a', 'T2a'), ('T2b', 'T2b'), ('T3a', 'T3a'), ('T3b', 'T3b'), ('T4a', 'T4a'), ('T4b', 'T4b')], max_length=10, null=True)),
                ('prim', models.CharField(blank=True, choices=[('primary', 'Primary'), ('metastasis', 'Metastasis')], max_length=10, null=True)),
                ('subtype', models.CharField(blank=True, max_length=120, null=True)),
                ('slides', models.IntegerField(blank=True, null=True)),
                ('slides_left', models.IntegerField(blank=True, null=True)),
                ('fixation', models.CharField(blank=True, max_length=10, null=True)),
                ('storage', models.CharField(blank=True, max_length=50, null=True)),
                ('scan_number', models.CharField(blank=True, max_length=200, null=True)),
                ('icd10', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('micro', models.TextField(blank=True, null=True)),
                ('gross', models.TextField(blank=True, null=True)),
                ('clinical', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('old_body_site', models.CharField(blank=True, max_length=600, null=True)),
                ('collection', models.CharField(choices=[('PU', 'Punch'), ('SC', 'Scraping'), ('PE', 'Cell Pellet'), ('CU', 'Curls')], default='SC', max_length=2)),
                ('path_note', models.TextField(blank=True, null=True)),
                ('ip_dx', models.TextField(blank=True, null=True)),
                ('body_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='body.body')),
                ('patient', models.ForeignKey(blank=True, db_column='patient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_blocks', to='lab.patients')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_blocks', to='projects.projects')),
            ],
            options={
                'db_table': 'blocks',
                'managed': True,
            },
        ),
    ]
