# Generated by Django 3.2.15 on 2022-09-02 19:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_auto_20200716_0021'),
        ('lab', '0033_auto_20220902_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('old_block_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('pat_id', models.CharField(blank=True, max_length=12, null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1, message='Minimum age is 0.1 years'), django.core.validators.MaxValueValidator(120, message='Maximum age is 120 years')])),
                ('body_site', models.TextField(blank=True, null=True)),
                ('ulceration', models.BooleanField(blank=True, null=True)),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mitoses', models.IntegerField(blank=True, null=True)),
                ('p_stage', models.TextField(blank=True, null=True)),
                ('prim', models.TextField(blank=True, null=True)),
                ('subtype', models.TextField(blank=True, null=True)),
                ('slides', models.IntegerField(blank=True, null=True)),
                ('slides_left', models.IntegerField(blank=True, null=True)),
                ('fixation', models.CharField(blank=True, max_length=10, null=True)),
                ('area_id', models.CharField(blank=True, max_length=100, null=True)),
                ('old_project', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('storage', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('micro', models.TextField(blank=True, null=True)),
                ('gross', models.TextField(blank=True, null=True)),
                ('clinical', models.TextField(blank=True, null=True)),
                ('site_code', models.TextField(blank=True, null=True)),
                ('icd9', models.TextField(blank=True, null=True)),
                ('bl_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now=True, null=True)),
                ('patient', models.ForeignKey(blank=True, db_column='patient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_blocks', to='lab.patients')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.projects')),
            ],
            options={
                'db_table': 'blocks',
                'managed': True,
            },
        ),
    ]
