# Generated by Django 3.1 on 2020-04-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='permalink',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
