"""
Django settings for test1 project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

from pathlib import Path
import os
import json
from django.contrib.messages import constants as message_constants

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

MESSAGE_LEVEL = message_constants.DEBUG


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent.parent

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = "/media/"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e6l2xn#ojz2g=tlgloq*oo*kxm)3z*8pcl*6e^)$n@-u8=n*s&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['melanomalab.ucsf.edu', '10.91.62.76', 'localhost']

# Application definition

INSTALLED_APPS = [
    # 'accession.apps.AccessionConfig',
    'libprep.apps.LibprepConfig',
    'lab.apps.LabConfig',
    'projects.apps.ProjectsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'crispy_forms',
    'home.apps.HomeConfig',
    'authentication.apps.AuthenticationConfig',
    'group.apps.GroupConfig',
    'account.apps.AccountConfig',
    'blocks.apps.BlocksConfig',
    'areas.apps.AreasConfig',
    'areatype.apps.AreatypeConfig',
    'core.apps.CoreConfig',
    'method.apps.MethodConfig',
    'samplelib.apps.SamplelibConfig',
    'capturedlib.apps.CapturedlibConfig',
    'sequencinglib',
    'sequencingrun',
    'buffer',
    'bait',
    'body',
    'barcodeset',
    'migration',
    'sequencingfile',
    'variant.apps.VariantConfig',
    'gene',
    'sheet',
    'wiki',
    'analysisrun',
    'cns',
    'qc',
    'channels',
    'jobs',
    'notification',
    'file_manager',
    'gpt',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_FAIL_SILENTLY = not DEBUG

# ===============================
# AWS S3 STORAGE CONFIGURATION
# ===============================
INSTALLED_APPS += ["storages"]

AWS_S3_REGION_NAME = "us-west-2"
AWS_STORAGE_BUCKET_NAME = "bastian-lab-169-3-r-us-west-2.sec.ucsf.edu"
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = "path"  # required for dotted bucket names

# Optional: object parameters (ensure the KMS alias exists & IAM allows kms:Encrypt)
AWS_S3_OBJECT_PARAMETERS = {
    "ServerSideEncryption": "aws:kms",
    "SSEKMSKeyId": "alias/managed-s3-key",
    "CacheControl": "max-age=86400",
}

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "region_name": AWS_S3_REGION_NAME,
            "default_acl": "private",
            "file_overwrite": False,
            "object_parameters": AWS_S3_OBJECT_PARAMETERS,
            "addressing_style": AWS_S3_ADDRESSING_STYLE,
            "signature_version": AWS_S3_SIGNATURE_VERSION,
        },
    },
    "staticfiles": {  # STATIC files collected to STATIC_ROOT
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        # or for cache-busting:
        # "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'core.log_streaming.AsyncLogStreamMiddleware'
]

ROOT_URLCONF = 'test1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'test1/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'test1.wsgi.application'
ASGI_APPLICATION = "test1.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],  # Redis server
        },
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/0',  # Use Redis database 0 for caching
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    'TIMEOUT': 300,
    }
}

# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

secret_path = Path(__file__).resolve().parent.parent / "db_connection.json"
RDS_SECRET = json.loads(secret_path.read_text())

DATABASES = {
    "default": {
        "ENGINE":   "django.db.backends.postgresql",
        "NAME":     RDS_SECRET["dbname"],
        "USER":     RDS_SECRET["username"],
        "PASSWORD": RDS_SECRET['password'],
        "HOST":     RDS_SECRET["host"],
        "PORT":     RDS_SECRET["port"],
        "OPTIONS": {
            "sslmode": "require",
            "options": "-c search_path=public,cosmic_hg38"
        },
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'test1/static'),
]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
APPEND_SLASH = True

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

# Authentication settings
LOGIN_URL = '/auth/login'
LOGOUT_URL = '/auth/logout'
LOGIN_REDIRECT_URL = '/projects'

TECHNICIAN_GROUP_NAME = "Technicians"
RESEARCHER_GROUP_NAME = "Researchers"
PI_GROUP_NAME = "Primary Investigators"

# BastianRaid directories
BASTIANRAID_DIRECTORY = "BastianRaid-02"
TEMP_DIRECTORY = f"{BASTIANRAID_DIRECTORY}/TEMP"
HISEQDATA_DIRECTORY = f"{BASTIANRAID_DIRECTORY}/HiSeqData"


# SequencingData directories
SMB_DIRECTORY_SEQUENCINGDATA = f"s3://{AWS_STORAGE_BUCKET_NAME}/sequencingdata"
SEQUENCING_FILES_SOURCE_DIRECTORY = f"{SMB_DIRECTORY_SEQUENCINGDATA}/ProcessedData"
SEQUENCING_FILES_DESTINATION_DIRECTORY = SEQUENCING_FILES_SOURCE_DIRECTORY

# Variant data
VARIANT_FILES_SOURCE_DIRECTORY = SEQUENCING_FILES_SOURCE_DIRECTORY


# # ================================
# # EMAIL CONFIGURATION (POSTFIX)
# # ================================
# SMTP_CONFIG_PATH = BASE_DIR / "test1" / "smtp.json"
#
# if SMTP_CONFIG_PATH.exists():
#     with open(SMTP_CONFIG_PATH) as f:
#         smtp_config = json.load(f)
#
#     EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#     EMAIL_HOST = smtp_config.get("EMAIL_HOST")
#     EMAIL_PORT = smtp_config.get("EMAIL_PORT", 587)
#     EMAIL_USE_TLS = smtp_config.get("EMAIL_USE_TLS", True)
#     EMAIL_USE_SSL = smtp_config.get("EMAIL_USE_SSL", False)
#     EMAIL_HOST_USER = smtp_config.get("EMAIL_HOST_USER")
#     EMAIL_HOST_PASSWORD = smtp_config.get("EMAIL_HOST_PASSWORD")
#     DEFAULT_FROM_EMAIL = smtp_config.get(
#         "DEFAULT_FROM_EMAIL",
#         EMAIL_HOST_USER
#     )
#
# else:
#     raise FileNotFoundError(f"SMTP config not found: {SMTP_CONFIG_PATH}")



