# Generated by Django 3.2.15 on 2022-10-08 13:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0003_areas_old_area_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NucAcids',
            fields=[
                ('nu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='NA ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Extraction Date')),
                ('method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Extraction Method')),
                ('na_type', models.CharField(choices=[('dna', 'DNA'), ('rna', 'RNA'), ('both', 'Both DNA and RNA')], max_length=4)),
                ('qubit', models.FloatField(blank=True, null=True, verbose_name='Qubit')),
                ('vol_init', models.FloatField(blank=True, null=True, verbose_name='Volume Initialize')),
                ('vol_remain', models.FloatField(blank=True, null=True, verbose_name='Volume Remain')),
                ('notes', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, db_column='area', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_nucacids', to='areas.areas')),
            ],
            options={
                'db_table': 'nuc_acids',
            },
        ),
    ]
