# Generated by Django 3.2.15 on 2023-11-14 21:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('method', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NucAcids',
            fields=[
                ('nu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='NA ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Extraction Date')),
                ('na_type', models.CharField(blank=True, choices=[('dna', 'DNA'), ('rna', 'RNA'), ('both', 'Both DNA and RNA')], max_length=4, null=True, verbose_name='NA Type')),
                ('conc', models.FloatField(default=0, verbose_name='Concentration')),
                ('vol_init', models.FloatField(default=0, verbose_name='Volume Initialize')),
                ('vol_remain', models.FloatField(default=0, verbose_name='Volume Remain')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('area', models.ForeignKey(blank=True, db_column='area', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nucacids', to='areas.areas', verbose_name='Area')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nuc_acids', to='method.method', verbose_name='Method')),
            ],
            options={
                'db_table': 'nuc_acids',
            },
        ),
    ]
