# Generated by Django 3.0.5 on 2020-07-14 19:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0015_auto_20200714_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='NucAcids',
            fields=[
                ('old_na_id', models.CharField(blank=True, max_length=50, null=True)),
                ('old_area_id', models.CharField(blank=True, max_length=50, null=True)),
                ('na_type', models.CharField(blank=True, max_length=20, null=True)),
                ('date_extr', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('qubit', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('re_ext', models.FloatField(blank=True, null=True)),
                ('total_ext', models.FloatField(blank=True, null=True)),
                ('na_sheared', models.FloatField(blank=True, null=True)),
                ('shearing_vol', models.FloatField(blank=True, null=True)),
                ('te_vol', models.FloatField(blank=True, null=True)),
                ('sl_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('projects', models.CharField(blank=True, max_length=100, null=True)),
                ('nu_id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.ForeignKey(blank=True, db_column='area', null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.Areas')),
            ],
            options={
                'db_table': 'nuc_acids',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SampleLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_id', models.CharField(blank=True, max_length=50, null=True)),
                ('na_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_pcr', models.IntegerField(blank=True, null=True)),
                ('post_lib_qubit', models.FloatField(blank=True, null=True)),
                ('post_lib_qpcr', models.FloatField(blank=True, null=True)),
                ('vol_lib', models.IntegerField(blank=True, null=True)),
                ('lp_dna', models.FloatField(blank=True, null=True)),
                ('re_lp_amount', models.FloatField(blank=True, null=True)),
                ('re_lp2_amount', models.FloatField(blank=True, null=True)),
                ('total_lp_dna', models.FloatField(blank=True, null=True)),
                ('chosen_for_capt', models.CharField(blank=True, max_length=30, null=True)),
                ('input_dna', models.FloatField(blank=True, null=True)),
                ('input_vol', models.FloatField(blank=True, null=True)),
                ('post_pcr', models.IntegerField(blank=True, null=True)),
                ('barcode_id', models.CharField(blank=True, max_length=50, null=True)),
                ('prep_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.CharField(blank=True, max_length=50, null=True)),
                ('nuc_acid', models.ForeignKey(blank=True, db_column='nuc_acid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='libprep.NucAcids')),
            ],
            options={
                'db_table': 'sample_lib',
                'managed': True,
            },
        ),
    ]
