# Generated by Django 3.0.5 on 2020-07-14 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libprep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplelib',
            name='nuc_acid',
            field=models.ForeignKey(blank=True, db_column='nuc_acid', null=True, on_delete=django.db.models.deletion.CASCADE, to='libprep.NucAcids'),
        ),
    ]
