# Generated by Django 3.0.5 on 2020-07-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libprep', '0002_auto_20200714_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nucacids',
            old_name='old_na_id',
            new_name='na_id',
        ),
    ]
