# Generated by Django 3.0.5 on 2020-07-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_auto_20200714_1921'),
        ('libprep', '0004_auto_20200714_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucacids',
            name='area',
            field=models.ForeignKey(blank=True, db_column='area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.Areas'),
        ),
    ]
