# Generated by Django 3.0.5 on 2020-10-14 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessions',
            fields=[
                ('dept_number', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('pathologist', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('dept_code', models.TextField(blank=True, null=True)),
                ('specimen_count', models.IntegerField(blank=True, null=True)),
                ('clinical', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IpPatients',
            fields=[
                ('pat_id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unipats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('block_id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('site_code', models.TextField(blank=True, null=True)),
                ('dx_text', models.TextField(blank=True, null=True)),
                ('clinical', models.TextField(blank=True, null=True)),
                ('gross', models.TextField(blank=True, null=True)),
                ('micro', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('cpt_code', models.TextField(blank=True, null=True)),
                ('dx_code', models.TextField(blank=True, null=True)),
                ('icd9', models.TextField(blank=True, null=True)),
                ('site_text', models.TextField(blank=True, null=True)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accession.Accessions')),
            ],
            options={
                'db_table': 'parts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Melanomas',
            fields=[
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accession.Parts')),
                ('p_stage', models.TextField(blank=True, null=True)),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('ulceration', models.BooleanField(blank=True, null=True)),
                ('mitoses', models.IntegerField(blank=True, null=True)),
                ('primary', models.TextField(blank=True, null=True)),
                ('subtype', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'melanomas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Outcomes',
            fields=[
                ('ccr_patient_id', models.TextField(unique=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accession.IpPatients')),
                ('c_stage', models.TextField(blank=True, null=True)),
                ('cause_of_death', models.TextField(blank=True, null=True)),
                ('nodes_sampled', models.TextField(blank=True, null=True)),
                ('nodes_positive', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('ccr_datestat_decode', models.TextField(blank=True, null=True)),
                ('months_survived', models.TextField(blank=True, null=True)),
                ('date_last_contact_or_death', models.TextField(blank=True, null=True)),
                ('vital_status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outcomes',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='accessions',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accession.IpPatients'),
        ),
    ]
