# Generated by Django 3.0.5 on 2020-10-14 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='melanomas',
            old_name='primary',
            new_name='prim',
        ),
    ]
