# Generated by Django 3.0.5 on 2020-10-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0003_auto_20201014_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melanomas',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
