# Generated by Django 3.0.5 on 2020-10-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0004_auto_20201014_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcomes',
            name='ccr_patient_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
