# Generated by Django 3.0.5 on 2020-10-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0005_auto_20201014_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippatients',
            name='race',
            field=models.TextField(blank=True, null=True),
        ),
    ]
