# Generated by Django 3.2.15 on 2022-09-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('pat_id', models.CharField(max_length=12, unique=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('dob', models.IntegerField(blank=True, null=True)),
                ('race', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('blocks_temp', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=50, null=True)),
                ('pa_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
                'managed': True,
            },
        ),
    ]
