# Generated by Django 3.0.5 on 2020-05-16 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('old_area_id', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=6, null=True)),
                ('old_block_id', models.CharField(blank=True, max_length=50, null=True)),
                ('collection', models.CharField(blank=True, max_length=50, null=True)),
                ('area_type', models.CharField(blank=True, max_length=50, null=True)),
                ('he_image', models.CharField(blank=True, max_length=200, null=True)),
                ('na_id', models.CharField(blank=True, max_length=50, null=True)),
                ('completion_date', models.CharField(blank=True, max_length=20, null=True)),
                ('investigator', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('ar_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'areas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NucAcids',
            fields=[
                ('old_na_id', models.CharField(blank=True, max_length=50, null=True)),
                ('old_area_id', models.CharField(blank=True, max_length=50, null=True)),
                ('na_type', models.CharField(blank=True, max_length=20, null=True)),
                ('date_extr', models.DateField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('qubit', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('re_ext', models.FloatField(blank=True, null=True)),
                ('total_ext', models.FloatField(blank=True, null=True)),
                ('na_sheared', models.FloatField(blank=True, null=True)),
                ('shearing_vol', models.FloatField(blank=True, null=True)),
                ('te_vol', models.FloatField(blank=True, null=True)),
                ('sl_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('projects', models.CharField(blank=True, max_length=100, null=True)),
                ('nu_id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.ForeignKey(blank=True, db_column='area', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lab.Areas')),
            ],
            options={
                'db_table': 'nuc_acids',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('pat_id', models.CharField(blank=True, max_length=12, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('age', models.FloatField(blank=True, null=True)),
                ('race', models.CharField(blank=True, max_length=1, null=True)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('blocks_temp', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.CharField(blank=True, max_length=50, null=True)),
                ('pa_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SampleLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_id', models.CharField(blank=True, max_length=50, null=True)),
                ('na_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_pcr', models.IntegerField(blank=True, null=True)),
                ('post_lib_qubit', models.FloatField(blank=True, null=True)),
                ('post_lib_qpcr', models.FloatField(blank=True, null=True)),
                ('vol_lib', models.IntegerField(blank=True, null=True)),
                ('lp_dna', models.FloatField(blank=True, null=True)),
                ('re_lp_amount', models.FloatField(blank=True, null=True)),
                ('re_lp2_amount', models.FloatField(blank=True, null=True)),
                ('total_lp_dna', models.FloatField(blank=True, null=True)),
                ('chosen_for_capt', models.CharField(blank=True, max_length=30, null=True)),
                ('input_dna', models.FloatField(blank=True, null=True)),
                ('input_vol', models.FloatField(blank=True, null=True)),
                ('post_pcr', models.IntegerField(blank=True, null=True)),
                ('barcode_id', models.CharField(blank=True, max_length=50, null=True)),
                ('prep_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.CharField(blank=True, max_length=50, null=True)),
                ('nuc_acid', models.ForeignKey(blank=True, db_column='nuc_acid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lab.NucAcids')),
            ],
            options={
                'db_table': 'sample_lib',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('old_block_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pat_id', models.CharField(blank=True, max_length=12, null=True)),
                ('body_site', models.CharField(blank=True, max_length=200, null=True)),
                ('ulceration', models.BooleanField(blank=True, null=True)),
                ('slides', models.IntegerField(blank=True, null=True)),
                ('slides_left', models.IntegerField(blank=True, null=True)),
                ('fixation', models.CharField(blank=True, max_length=10, null=True)),
                ('area_id', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=50, null=True)),
                ('storage', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('bl_id', models.AutoField(primary_key=True, serialize=False)),
                ('receive', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, db_column='patient', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lab.Patients')),
            ],
            options={
                'db_table': 'blocks',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='areas',
            name='block',
            field=models.ForeignKey(blank=True, db_column='block', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lab.Blocks'),
        ),
    ]
