# Generated by Django 3.0.5 on 2020-05-16 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='patient',
            field=models.ForeignKey(blank=True, db_column='patient', null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.Patients'),
        ),
    ]
