# Generated by Django 3.0.5 on 2020-05-16 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20200516_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='block',
            field=models.ForeignKey(blank=True, db_column='block', null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.Blocks'),
        ),
        migrations.AlterField(
            model_name='nucacids',
            name='area',
            field=models.ForeignKey(blank=True, db_column='area', null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.Areas'),
        ),
    ]
