# Generated by Django 3.0.5 on 2020-05-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20200516_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='pat_id',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='project',
            field=models.TextField(blank=True, null=True),
        ),
    ]
