# Generated by Django 3.0.5 on 2020-05-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20200520_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='project',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
