# Generated by Django 3.0.5 on 2020-05-21 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20200520_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='age',
        ),
        migrations.AddField(
            model_name='blocks',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator('0.1', message='Age has to be >0.1')]),
        ),
        migrations.AddField(
            model_name='patients',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
