# Generated by Django 3.0.5 on 2020-05-22 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_auto_20200521_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.1, message='Minimum age is 0.1 years'), django.core.validators.MaxValueValidator(120, message='Maximum age is 120 years')]),
        ),
    ]
