# Generated by Django 3.0.5 on 2020-05-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_auto_20200522_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocks',
            name='receive',
        ),
        migrations.AddField(
            model_name='blocks',
            name='date_added',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
