# Generated by Django 3.0.5 on 2020-05-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_auto_20200522_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
