# Generated by Django 3.0.5 on 2020-05-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_auto_20200522_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='completion_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
