# Generated by Django 3.0.5 on 2020-05-26 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_auto_20200525_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='completion_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
