# Generated by Django 3.0.5 on 2020-05-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_auto_20200526_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
