# Generated by Django 3.0.5 on 2020-05-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_areas_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d'),
        ),
    ]
