# Generated by Django 3.0.5 on 2020-07-14 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_auto_20200527_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplelib',
            name='nuc_acid',
        ),
        migrations.DeleteModel(
            name='NucAcids',
        ),
        migrations.DeleteModel(
            name='SampleLib',
        ),
    ]
