# Generated by Django 3.0.5 on 2020-10-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_auto_20200714_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='dob',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
