# Generated by Django 3.0.5 on 2020-10-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_auto_20201013_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='mitoses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blocks',
            name='p_stage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blocks',
            name='prim',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blocks',
            name='subtype',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blocks',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
