# Generated by Django 3.0.5 on 2020-10-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0017_auto_20201016_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='body_site',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
