# Generated by Django 3.0.5 on 2020-10-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_auto_20201016_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='race',
            field=models.TextField(blank=True, null=True),
        ),
    ]
