# Generated by Django 3.0.5 on 2020-10-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0019_auto_20201020_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocks',
            old_name='project',
            new_name='old_project',
        ),
    ]
