# Generated by Django 3.0.5 on 2020-10-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0021_blocks_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocks',
            name='project',
        ),
    ]
