# Generated by Django 3.0.5 on 2020-10-23 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200716_0021'),
        ('lab', '0022_remove_blocks_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Projects'),
        ),
    ]
