# Generated by Django 3.0.5 on 2020-12-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0023_blocks_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='clinical',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blocks',
            name='gross',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blocks',
            name='icd9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blocks',
            name='micro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blocks',
            name='site_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
