# Generated by Django 3.0.5 on 2021-01-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0024_auto_20201217_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='old_area_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
