# Generated by Django 3.0.5 on 2021-01-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0026_auto_20210107_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='collection',
            field=models.CharField(blank=True, default='PU', max_length=20, null=True),
        ),
    ]
