# Generated by Django 3.0.5 on 2021-01-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0027_auto_20210107_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='collection',
            field=models.CharField(blank=True, default='SC', max_length=2, null=True),
        ),
    ]
