# Generated by Django 3.0.5 on 2021-01-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0028_auto_20210107_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='collection',
            field=models.CharField(blank=True, choices=[('PU', 'Punch'), ('SC', 'Scraping'), ('PE', 'Cell Pellet'), ('CU', 'Curls')], default='SC', max_length=2, null=True),
        ),
    ]
