# Generated by Django 3.0.5 on 2021-01-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0029_auto_20210107_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='area_type',
            field=models.CharField(blank=True, choices=[('IS', 'In Situ'), ('INV', 'Invasive'), ('N', 'Normal'), ('ST', 'Stroma'), ('INT', 'Intermediate')], max_length=50, null=True),
        ),
    ]
