# Generated by Django 3.0.5 on 2021-01-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0030_auto_20210108_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='area_type',
            field=models.CharField(choices=[('T', 'TUmor'), ('IS', 'In Situ'), ('INV', 'Invasive'), ('N', 'Normal'), ('ST', 'Stroma'), ('INT', 'Intermediate')], default='T', max_length=50),
        ),
    ]
