# Generated by Django 3.2.15 on 2022-08-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0031_auto_20210108_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='area_type',
            field=models.CharField(choices=[('T', 'Malignant Tumor, NOS'), ('IS', 'Malignant Tumor, In Situ'), ('INV', 'Malignant Tumor, Invasive'), ('B', 'Benign Tumor (e.g. Nevus)'), ('N', 'Normal'), ('ST', 'Stroma'), ('INT', 'Intermediate Tumor')], default='T', max_length=50),
        ),
    ]
