# Generated by Django 3.2.15 on 2022-09-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0032_alter_areas_area_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areas',
            name='block',
        ),
        migrations.DeleteModel(
            name='Blocks',
        ),
    ]
