# Generated by Django 3.2.15 on 2022-09-02 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
        ('lab', '0033_auto_20220902_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='block',
            field=models.ForeignKey(blank=True, db_column='block', null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.blocks'),
        ),
    ]
