# Generated by Django 3.2.15 on 2022-09-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0034_areas_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areas',
            name='block',
        ),
    ]
