# Generated by Django 3.1 on 2020-04-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('pat_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('age', models.FloatField(blank=True, null=True)),
                ('race', models.CharField(blank=True, max_length=1, null=True)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('blocks_temp', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'patients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('block_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('body_site', models.CharField(blank=True, max_length=200, null=True)),
                ('ulceration', models.BooleanField(blank=True, null=True)),
                ('slides', models.IntegerField(blank=True, null=True)),
                ('slides_left', models.IntegerField(blank=True, null=True)),
                ('fixation', models.CharField(blank=True, max_length=10, null=True)),
                ('project', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=50, null=True)),
                ('storage', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('receive', models.DateField(blank=True, null=True)),
                ('pat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.patients')),
            ],
            options={
                'db_table': 'blocks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('area_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('area', models.CharField(blank=True, max_length=6, null=True)),
                ('collection', models.CharField(blank=True, max_length=50, null=True)),
                ('area_type', models.CharField(blank=True, max_length=50, null=True)),
                ('he_image', models.CharField(blank=True, max_length=200, null=True)),
                ('completion_date', models.CharField(blank=True, max_length=20, null=True)),
                ('investigator', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.blocks')),
            ],
            options={
                'db_table': 'areas',
                'managed': True,
            },
        ),
    ]
