# Generated by Django 3.1 on 2020-04-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_tpats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpats',
            name='FIELDNAME',
        ),
        migrations.AddField(
            model_name='tpats',
            name='notes',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
