# Generated by Django 3.0.5 on 2020-05-14 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20200417_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'managed': True, 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.RemoveField(
            model_name='blocks',
            name='pat',
        ),
        migrations.AddField(
            model_name='blocks',
            name='pat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.Patients'),
        ),
    ]
