# Generated by Django 3.0.5 on 2020-05-16 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20200514_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_id', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode_name', models.CharField(blank=True, max_length=50, null=True)),
                ('index_i7', models.CharField(blank=True, max_length=20, null=True)),
                ('index_i5_nova_hi2500', models.CharField(blank=True, max_length=20, null=True)),
                ('index_i5_hi4000', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'barcodes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NucAcids',
            fields=[
                ('old_na_id', models.CharField(blank=True, max_length=50, null=True)),
                ('old_area_id', models.CharField(blank=True, max_length=50, null=True)),
                ('na_type', models.CharField(blank=True, max_length=20, null=True)),
                ('date_extr', models.DateField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('qubit', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('re_ext', models.FloatField(blank=True, null=True)),
                ('total_ext', models.FloatField(blank=True, null=True)),
                ('na_sheared', models.FloatField(blank=True, null=True)),
                ('shearing_vol', models.FloatField(blank=True, null=True)),
                ('te_vol', models.FloatField(blank=True, null=True)),
                ('sl_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('projects', models.CharField(blank=True, max_length=100, null=True)),
                ('nu_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nuc_acids',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SampleLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_id', models.CharField(blank=True, max_length=50, null=True)),
                ('na_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_pcr', models.IntegerField(blank=True, null=True)),
                ('post_lib_qubit', models.FloatField(blank=True, null=True)),
                ('post_lib_qpcr', models.FloatField(blank=True, null=True)),
                ('vol_lib', models.IntegerField(blank=True, null=True)),
                ('lp_dna', models.FloatField(blank=True, null=True)),
                ('re_lp_amount', models.FloatField(blank=True, null=True)),
                ('re_lp2_amount', models.FloatField(blank=True, null=True)),
                ('total_lp_dna', models.FloatField(blank=True, null=True)),
                ('chosen_for_capt', models.CharField(blank=True, max_length=30, null=True)),
                ('input_dna', models.FloatField(blank=True, null=True)),
                ('input_vol', models.FloatField(blank=True, null=True)),
                ('post_pcr', models.IntegerField(blank=True, null=True)),
                ('barcode_id', models.CharField(blank=True, max_length=50, null=True)),
                ('prep_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.CharField(blank=True, max_length=50, null=True)),
                ('nuc_acid', models.ForeignKey(blank=True, db_column='nuc_acid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lab.NucAcids')),
            ],
            options={
                'db_table': 'sample_lib',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Tpats',
        ),
        migrations.RemoveField(
            model_name='areas',
            name='area_id',
        ),
        migrations.RemoveField(
            model_name='blocks',
            name='block_id',
        ),
        migrations.AddField(
            model_name='areas',
            name='ar_id',
            field=models.AutoField(primary_key=True, serialize=True, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areas',
            name='na_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='areas',
            name='old_area_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='areas',
            name='old_block_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blocks',
            name='area_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blocks',
            name='bl_id',
            field=models.AutoField(primary_key=True, serialize=True, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blocks',
            name='old_block_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blocks',
            name='patient',
            field=models.ForeignKey(blank=True, db_column='patient', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lab.Patients'),
        ),
        migrations.AddField(
            model_name='patients',
            name='pa_id',
            field=models.AutoField(primary_key=True, serialize=True, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areas',
            name='block',
            field=models.ForeignKey(blank=True, db_column='block', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lab.Blocks'),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='pat_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='pat_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='nucacids',
            name='area',
            field=models.ForeignKey(blank=True, db_column='area', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lab.Areas'),
        ),
    ]
